# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tcasale <tcasale@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/03/20 12:54:21 by tcasale           #+#    #+#              #
#    Updated: 2022/03/25 15:37:46 by tcasale          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
NAME	= get_next_line.a

SRCS	= get_next_line_bonus.c \
		get_next_line_utils_bonus.c

OBJS	= ${SRCS:.c=.o}

HEADER	= includes

CC		= gcc
RM		= rm -f
CFLAGS	= -Wall -Werror -Wextra
AR		= ar  rcs

%.o: %.c
	${CC} -c ${CFLAGS} -o $@ $<

all:	$(NAME)

$(NAME):	$(OBJS)
		$(AR) $@ $^

clean:
		${RM} ${OBJS}

fclean:	clean
		${RM} ${NAME}

re:		fclean all

.PHONY: all clean fclean re
